version: '3.8'

services:
  mapos:
    image: php:7.4-apache
    container_name: mapos_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: mapos_user
      DB_PASSWORD: mapos_pass
      DB_NAME: mapos_db
    depends_on:
      - db
    networks:
      - mapos_net

  db:
    image: mysql:5.7
    container_name: mapos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mapos
      MYSQL_USER: root
      MYSQL_PASSWORD: mapos
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mapos_net

networks:
  mapos_net:

volumes:
  db_data:
